In [2]:
import pandas as pd
import numpy as np

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Kernel is working!")

Pandas: 3.0.6
NumPy: 2.5.3
Kernel is working!

In [3]:
from pathlib import Path

raw_folder = Path("../data/raw")

files = list(raw_folder.glob("*.csv"))

print("CSV files found:")
for file in files:
    print(file)

csv_file = files[0]

df = pd.read_csv(csv_file)

print(f"\nLoaded: {csv_file.name}")
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]:,}")

df.head()

CSV files found:
..\data\raw\WA_FnUseC_TelcoCustomerChurn.csv

Loaded: WA_FnUseC_TelcoCustomerChurn.csv
Rows: 7,043
Columns: 21

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
# Basic dataset audit

print("Shape:")
print(df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isna().sum().sort_values(ascending=False))

print("\nDuplicate rows:")
print(df.duplicated().sum())

Shape:
(7043, 21)

Column names:
['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

Data types:
customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

Missing values:
customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

Duplicate rows:
0

In [5]:
# Basic numerical/statistical summary

df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
customerID,7043,7043,7590-VHVEG,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gender,7043,2,Male,3555,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SeniorCitizen,7043.0,NaN,NaN,NaN,0.162147,0.368612,0.0,0.0,0.0,0.0,1.0
Partner,7043,2,No,3641,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dependents,7043,2,No,4933,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tenure,7043.0,NaN,NaN,NaN,32.371149,24.559481,0.0,9.0,29.0,55.0,72.0
PhoneService,7043,2,Yes,6361,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MultipleLines,7043,3,No,3390,NaN,NaN,NaN,NaN,NaN,NaN,NaN
InternetService,7043,3,Fiber optic,3096,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OnlineSecurity,7043,3,No,3498,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OnlineBackup,7043,3,No,3088,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DeviceProtection,7043,3,No,3095,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TechSupport,7043,3,No,3473,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StreamingTV,7043,3,No,2810,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StreamingMovies,7043,3,No,2785,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Contract,7043,3,Month-to-month,3875,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PaperlessBilling,7043,2,Yes,4171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PaymentMethod,7043,4,Electronic check,2365,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MonthlyCharges,7043.0,NaN,NaN,NaN,64.761692,30.090047,18.25,35.5,70.35,89.85,118.75
TotalCharges,7043,6531,20.2,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Churn,7043,2,No,5174,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Check data types and blank values

print("DATA TYPES")
print(df.dtypes)

print("\nBLANK STRINGS")
for col in df.columns:
    blanks = (df[col].astype(str).str.strip() == "").sum()
    if blanks > 0:
        print(f"{col}: {blanks} blank values")

print("\nNaN VALUES")
print(df.isna().sum().sort_values(ascending=False))

DATA TYPES
customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

BLANK STRINGS
TotalCharges: 11 blank values

NaN VALUES
customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [7]:
# Inspect TotalCharges specifically

print("TotalCharges data type:", df["TotalCharges"].dtype)

print("\nBlank TotalCharges rows:")
print(df[df["TotalCharges"].astype(str).str.strip() == ""][["customerID", "tenure", "MonthlyCharges", "TotalCharges", "Churn"]])

TotalCharges data type: str

Blank TotalCharges rows:
      customerID  tenure  MonthlyCharges TotalCharges Churn
488   4472-LVYGI       0           52.55                 No
753   3115-CZMZD       0           20.25                 No
936   5709-LVOEQ       0           80.85                 No
1082  4367-NUYAO       0           25.75                 No
1340  1371-DWPAZ       0           56.05                 No
3331  7644-OMVMY       0           19.85                 No
3826  3213-VVOLG       0           25.35                 No
4380  2520-SGTTA       0           20.00                 No
5218  2923-ARZLG       0           19.70                 No
6670  4075-WKNIU       0           73.35                 No
6754  2775-SEFEE       0           61.90                 No

In [8]:
# Convert TotalCharges from text to numeric.
# Blank strings become NaN.

df["TotalCharges"] = pd.to_numeric(
    df["TotalCharges"],
    errors="coerce"
)

print("TotalCharges data type:")
print(df["TotalCharges"].dtype)

print("\nMissing TotalCharges after conversion:")
print(df["TotalCharges"].isna().sum())

TotalCharges data type:
float64

Missing TotalCharges after conversion:
11

In [9]:
missing_total = df[df["TotalCharges"].isna()]

print(missing_total[
    ["customerID", "tenure", "MonthlyCharges", "TotalCharges", "Churn"]
])

      customerID  tenure  MonthlyCharges  TotalCharges Churn
488   4472-LVYGI       0           52.55           NaN    No
753   3115-CZMZD       0           20.25           NaN    No
936   5709-LVOEQ       0           80.85           NaN    No
1082  4367-NUYAO       0           25.75           NaN    No
1340  1371-DWPAZ       0           56.05           NaN    No
3331  7644-OMVMY       0           19.85           NaN    No
3826  3213-VVOLG       0           25.35           NaN    No
4380  2520-SGTTA       0           20.00           NaN    No
5218  2923-ARZLG       0           19.70           NaN    No
6670  4075-WKNIU       0           73.35           NaN    No
6754  2775-SEFEE       0           61.90           NaN    No

In [10]:
# Fill missing TotalCharges for customers with zero tenure.
# These represent new customers with no accumulated charges.

mask = (df["TotalCharges"].isna()) & (df["tenure"] == 0)

print("Rows to fill:", mask.sum())

df.loc[mask, "TotalCharges"] = 0

print("Remaining missing TotalCharges:",
      df["TotalCharges"].isna().sum())

Rows to fill: 11
Remaining missing TotalCharges: 0

In [11]:
df.loc[mask, ["customerID", "tenure", "MonthlyCharges", "TotalCharges", "Churn"]]

      customerID  tenure  MonthlyCharges  TotalCharges Churn
488   4472-LVYGI       0           52.55           0.0    No
753   3115-CZMZD       0           20.25           0.0    No
936   5709-LVOEQ       0           80.85           0.0    No
1082  4367-NUYAO       0           25.75           0.0    No
1340  1371-DWPAZ       0           56.05           0.0    No
3331  7644-OMVMY       0           19.85           0.0    No
3826  3213-VVOLG       0           25.35           0.0    No
4380  2520-SGTTA       0           20.00           0.0    No
5218  2923-ARZLG       0           19.70           0.0    No
6670  4075-WKNIU       0           73.35           0.0    No
6754  2775-SEFEE       0           61.90           0.0    No

In [12]:
# Check for duplicate records and duplicate customer IDs

print("Duplicate rows:", df.duplicated().sum())
print("Duplicate customer IDs:", df["customerID"].duplicated().sum())

print("\nNumber of unique customers:", df["customerID"].nunique())
print("Number of rows:", len(df))

Duplicate rows: 0
Duplicate customer IDs: 0

Number of unique customers: 7043
Number of rows: 7043

In [13]:
# Check the Churn target

print(df["Churn"].value_counts())

print("\nChurn percentage:")
print(df["Churn"].value_counts(normalize=True).mul(100).round(2))

Churn
No     5174
Yes    1869
Name: count, dtype: int64

Churn percentage:
Churn
No     73.46
Yes    26.54
Name: proportion, dtype: float64

In [14]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate customer IDs:", df["customerID"].duplicated().sum())
print("Unique customers:", df["customerID"].nunique())
print("Total rows:", len(df))

Duplicate rows: 0
Duplicate customer IDs: 0
Unique customers: 7043
Total rows: 7043

In [15]:
# Inspect unique values in every categorical column

categorical_cols = df.select_dtypes(include="object").columns

for col in categorical_cols:
    print(f"\n{'=' * 50}")
    print(f"{col}")
    print(f"{'=' * 50}")
    print(df[col].value_counts(dropna=False))

==================================================
customerID
==================================================
customerID
7590-VHVEG    1
5575-GNVDE    1
3668-QPYBK    1
7795-CFOCW    1
9237-HQITU    1
             ..
6840-RESVB    1
2234-XADUH    1
4801-JZAZL    1
8361-LTMKD    1
3186-AJIEK    1
Name: count, Length: 7043, dtype: int64

==================================================
gender
==================================================
gender
Male      3555
Female    3488
Name: count, dtype: int64

==================================================
Partner
==================================================
Partner
No     3641
Yes    3402
Name: count, dtype: int64

==================================================
Dependents
==================================================
Dependents
No     4933
Yes    2110
Name: count, dtype: int64

==================================================
PhoneService
==================================================
PhoneService
Yes    6361
No      682
Name: count, dtype: int64

==================================================
MultipleLines
==================================================
MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

==================================================
InternetService
==================================================
InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

==================================================
OnlineSecurity
==================================================
OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

==================================================
OnlineBackup
==================================================
OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

==================================================
DeviceProtection
==================================================
DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

==================================================
TechSupport
==================================================
TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

==================================================
StreamingTV
==================================================
StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

==================================================
StreamingMovies
==================================================
StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

==================================================
Contract
==================================================
Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

==================================================
PaperlessBilling
==================================================
PaperlessBilling
Yes    4171
No     2872
Name: count, dtype: int64

==================================================
PaymentMethod
==================================================
PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

==================================================
Churn
==================================================
Churn
No     5174
Yes    1869
Name: count, dtype: int64

C:\Users\S K Varshini\AppData\Local\Temp\ipykernel_13816\1793901606.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns

In [16]:
# Create a cleaned copy of the dataset

df_clean = df.copy()

# Remove accidental leading/trailing whitespace from string columns
string_cols = df_clean.select_dtypes(include=["str", "object"]).columns

for col in string_cols:
    df_clean[col] = df_clean[col].str.strip()

# Verify the final structure
print("Rows:", len(df_clean))
print("Columns:", len(df_clean.columns))
print("Missing values:", df_clean.isna().sum().sum())
print("Duplicate rows:", df_clean.duplicated().sum())

Rows: 7043
Columns: 21
Missing values: 0
Duplicate rows: 0

In [17]:
from pathlib import Path

processed_folder = Path("../data/processed")
processed_folder.mkdir(parents=True, exist_ok=True)

output_file = processed_folder / "telco_customer_churn_clean.csv"

df_clean.to_csv(output_file, index=False)

print(f"Saved cleaned dataset to: {output_file}")

Saved cleaned dataset to: ..\data\processed\telco_customer_churn_clean.csv